SELECT DISTINCT PRIVILEGE FROM DBA_SYS_PRIVS;

SELECT DISTINCT PRIVILEGE FROM DBA_SYS_PRIVS
WHERE PRIVILEGE NOT LIKE '%ANY%';

SELECT * FROM DBA_USERS;


--DAR PERMISO AL USUARIO SCOTT PARA CREAR CUENTAS;

GRANT CREATE USER TO SCOTT;

--CREAR ACCESO AL LOGON A LA CUENTA SCOTT PARA CREAR ACCESO A LA CUENTA CREADA "POLLO"

GRANT CREATE SESSION TO SCOTT
 WITH ADMIN OPTION;

--PRIVILEGIOS PARA SCOTT

GRANT CREATE TABLE TO SCOTT
 WITH ADMIN OPTION;
 
--ASIGNAMOS CUOTA AL TABLESPACE DE LA CUENTA POLLO, ES MEJOR HACERLO DESDE SYSTEM

ALTER USER POLLO
      QUOTA 80 K ON USERS;
      
--PARA VER QUOTAS..
SELECT * FROM DBA_TS_QUOTAS;
 
SELECT * FROM DBA_USERS;

--PERMISO CREAR TABLAS MATERIALIZADAS HEREDADAS A SCOTT

GRANT CREATE MATERIALIZED VIEW TO SCOTT
 WITH ADMIN OPTION;
 
--PERMISO PARA QUITAR PRIVILEGIOS 

REVOKE CREATE MATERIALIZED VIEW FROM SCOTT;

--TRABAJOS CON LAS CLAVES
--CAMBIAR LA PASS
ALTER USER POLLO IDENTIFIED BY 2505;
--OBLIGAR A QUE EL USUARIO CAMBIE LA PASS
ALTER USER POLLO EXPIRE PASSWORD;

ALTER USER SCOTT IDENTIFIED BY HOLA;


--KILL USUARIOS
SELECT * FROM V$SESSION;
 WHERE USERNAME LIKE 'POLLO';
 
ALTER SYSTEM KILL SESSION '131,67'IMMEDIATE;
ALTER SYSTEM KILL SESSION '135,96'IMMEDIATE;


GRANT CREATE DATABASE LINK TO SCOTT;
