--CREATE USER <NOMBRE>
         --IDENTIFITED BY <ID_NOMBRE>
         --[DEFAULT TABLESPACE <NOMBRE>]
         --[TEMPORALY TABLESPACE <NOMBRE>]
         --[PROFILE <NOMBRE>]
         --[PASSWORD ESPYRE]
         --QUOTA{UNLIMITED/X/K/M}ON____
       
CREATE USER POLLO
    IDENTIFIED BY POLLITO; 

GRANT CREATE SESSION TO POLLO;

--CON SCOTT DAMOS DERECHOS A SCOTT PARA CREAR TABLAS

GRANT CREATE TABLE TO POLLO;

--CREAR VISTA A PABLO

GRANT CREATE MATERIALIZED VIEW TO POLLO;



---------------------EN USUARIOS SYSTEM: ---------------------------------

-----------CONCEDER DERECHOS

--SELECT DISTINCT PRIVILEGE FROM DBA_SYS_PRIVS;

--PARA DAR DERECHOS:
--SINTAXIS:

--GRANT CREATE USER TO <NOMBRE_USER> {USER/ROL/PUBLIC}[WHIT ADMIN OPTION];

-----------BORRAR DERECHOS

--REMOVE CREATE USER TO <NOMBRE>

--PARA BORRAR USUARIOS QUE HAYAN CREADO YA TABLAS POR EJEMPLO SE HACE CON CASCADE

--DROP USER <NOMBRE> [CASCADE]


--------------ASIGNAR DERECHOS........
--GRAN SELECT{{I,D,U,ALTER,EXJECUTE,REFERENCES,INDEX}ALL (TODOS LOS DERECHOS)}
--ON <OBJETO(TABLE)> TO {USER1,USER2,.../ROL/PUBLIC}
--[WITH GRANT OPTION]

--BORRAR IGUAL PERO REVOKE Y CAMBIAR TO POR FROM

--PARA QUE VEA LOS DERECHOS YA ASIGNADOS
SELECT * FROM USER_SYS_PRIVS;


---------------------------------------PARA DAR DERECHOS A UNA TABLA----------------------------------
GRANT SELECT ON EMPLE TO POLLO;

GRANT SELECT, INSERT, REFERENCES ON EMPLE TO POLLO;

--EN POLLO PARA VER LOS DERECHOS: SELECT * FROM USER_TAB_PRIVS;

GRANT CREATE SYNONYM TO POLLO;



--PRUEBA
 DROP TABLE ALUMNOS2_MOY;
 
 CREATE TABLE SANTI
 (DNI NUMBER PRIMARY KEY,
  CURSO VARCHAR2(1),
  IMPORTE NUMBER
  )
  
 PARTITION BY RANGE(IMPORTE)
  INTERVAL (500)
   SUBPARTITION BY LIST (CURSO)
    SUBPARTITION TEMPLATE
     (SUBPARTITION PRIMERO VALUES ('1'),
      SUBPARTITION SEGUNDO VALUES ('2')
      )
   (PARTITION UNO VALUES LESS THAN (500));
      

 INSERT INTO SANTI VALUES (123, '1',1000);
 INSERT INTO SANTI VALUES (321, '2',500);
 INSERT INTO SANTI VALUES (323, '1',300);

SELECT * FROM SANTI;

SELECT * FROM SANTI@PJJ;



-------------------------------DATABASE-------------------------------
--1. DAR PERMISO A DATABASE: GRANT CREATE DATABASE LINK TO SCOTT; OR GRANT CREATE PUBLIC DATABASE LINK TO SCOTT;
--2. CREAR EL DATABASE:
--   CREATE DATEBASE LINK <NOMBRE>
--   CONNECT TO <USUARIO_OBJETIVO>
--   IDENTIFIED BY <PASS_USUARIO_OBJETIVO> **NO PUEDE EMPEZAR POR NUMERO
--   USING <'NOMBRE_TSNAMES'>
--3.

CREATE TABLE TODOS
(LOC VARCHAR2(30),
 NUMERO NUMBER);
 
 INSERT INTO TODOS VALUES ('HOLA', 3);
  INSERT INTO TODOS VALUES ('ADIOS', 1);
   INSERT INTO TODOS VALUES ('VALLA', 2);
   
   SELECT * FROM TODOS;
 
 SELECT APELLIDO, LOC
 FROM EMPLE, TODOS
 WHERE DEPT_NO = NUMERO;
 
