--EJERCICIO TABLAS CLIENTES

            DROP TABLE CLIENTES;
CREATE TABLE CLIENTES
(DNI NUMBER CONSTRAINT PK_DNI_CLIENTES PRIMARY KEY,
 NOMBRE VARCHAR2 (30)
 );
        INSERT INTO CLIENTES VALUES (56898745,'PACO');
        
            DROP TABLE FACTURAS;
CREATE TABLE FACTURAS
(NUM_FACTURA NUMBER CONSTRAINT PK_NUM_FACTURA PRIMARY KEY,
 FECHA DATE,
 CLIENTE NUMBER CONSTRAINT FK_CLIENTE_FACTURAS FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (DNI),
 IMPORTE NUMBER
 );
        -- INSERT INTO FACTURAS VALUES 
        
        DROP TABLE PRODUCTO;
CREATE TABLE PRODUCTO
(COD_PRODUCTO NUMBER CONSTRAINT PK_COD_PRODUCTO_PRODUCTO PRIMARY KEY,
 DESCRIPCION VARCHAR2(30)
 );
             --INSERT
             
CREATE TABLE DETALLE
(COD_PRODUCTO NUMBER,
 NUM_FACTURA NUMBER,
 UNIDADES NUMBER,
 
 
  CONSTRAINT FK_NUM_FACTURA_DEE
