--EJERCICIO TABLAS HOSPITAL

            
            DROP TABLE HOSPITAL1;
CREATE TABLE HOSPITAL1
(HOSPITAL_COD NUMBER PRIMARY KEY ,
 NOMBRE VARCHAR2 (30),
 DIRECCION VARCHAR2 (30),
 TELEFONO NUMBER (10),
 NUM_CAMAS NUMBER CONSTRAINT C_CAMAS CHECK (NUM_CAMAS BETWEEN 100 AND 5000)
 );
 
           INSERT INTO HOSPITAL1 VALUES(1, 'SAURON', 'MORDOR', 666, 300);
 
           DROP TABLE DOCTOR1;
CREATE TABLE DOCTOR1
(DOCTOR_NO NUMBER CONSTRAINT DOC_DOCTOR CHECK (DOCTOR_NO <> 10 AND DOCTOR_NO <> 100 AND DOCTOR_NO <= 5) PRIMARY KEY,
 APELLIDO VARCHAR2 (20),
 ESPECIALIDAD VARCHAR2 (15),
 SALARIO NUMBER DEFAULT 500000,
 HOSPITAL_COD NUMBER,
              CONSTRAINT FK_HOPITAL_COD FOREIGN KEY (HOSPITAL_COD) REFERENCES HOSPITAL1(HOSPITAL_COD)
 );
              INSERT INTO DOCTOR1 VALUES(3, 'HOUSE', 'MATASANOS', 100000, 1);
              INSERT INTO DOCTOR1 (DOCTOR_NO, APELLIDO, ESPECIALIDAD, HOSPITAL_COD) VALUES(5, 'ELMEJOR', 'CIRUJANOOO', 1);
 
              DROP TABLE SALA1;
CREATE TABLE SALA1
(SALA_COD NUMBER PRIMARY KEY,
 NOMBRE VARCHAR2 (20) CONSTRAINT NOMBRE_SALA CHECK (LPAD(NOMBRE,5,1) LIKE 'PISO%'),
 NUM_CAMAS NUMBER CONSTRAINT NUM_CAMAS CHECK (NUM_CAMAS BETWEEN 50 AND 100),
 HOSPITAL_COD NUMBER, 
              CONSTRAINT FK_HOPITAL_COD_SALAS FOREIGN KEY (HOSPITAL_COD) REFERENCES HOSPITAL1(HOSPITAL_COD) 
 );
              INSERT INTO SALA1 VALUES(1, 'PISOTERRORIFICO', 56, 1);
              INSERT INTO SALA1 VALUES(2, 'PISOTERRORIFICO', 56, 2);--CASCA NO ESTA CREADO EL COD_HOPITAL 2
              
              DROP TABLE PLANTILLA1;
CREATE TABLE PLANTILLA1
(EMPLEADO_NO NUMBER PRIMARY KEY,
 APELLIDO VARCHAR2 (20),
 FUNCION VARCHAR2 (15) CONSTRAINT FUNCION_SER CHECK (FUNCION IN ('ENFERMERO', 'ENFERMERA', 'INTERNO')),
 TURNO VARCHAR2 (1) CONSTRAINT TURNO_NO CHECK (TURNO IN ('M', 'N', 'T')),
 SALARIO NUMBER,
 SALA_COD NUMBER,
              CONSTRAINT FK_SALA_COD_PLANTILLA FOREIGN KEY (SALA_COD) REFERENCES SALA1(SALA_COD)
); 
              INSERT INTO PLANTILLA1 VALUES(1, 'NONONO', 'ENFERMERO', 'M', 3000, 1);              

              DROP TABLE OCUPACION1;
CREATE TABLE OCUPACION1
(CAMA NUMBER PRIMARY KEY,
 SALA_COD NUMBER,
              CONSTRAINT FK_SALA_COD_OCUPACION FOREIGN KEY (SALA_COD) REFERENCES SALA1(SALA_COD)
);
              INSERT INTO OCUPACION1 VALUES (4, 1);
              INSERT INTO OCUPACION1 VALUES (4, 2);--CASCA NO CREADA LA PK EN SALA1

              DROP TABLE ENFERMO1;
CREATE TABLE ENFERMO1
(INSCRIPCION NUMBER PRIMARY KEY,
 APELLIDO VARCHAR2 (30),
 DIRECCION VARCHAR2 (30),
 FECHA_NAC DATE,
 SEXO VARCHAR2 (1) CONSTRAINT SEXO_ENFERMO CHECK (SEXO IN ('M', 'H', 'm', 'h')),
 NSS NUMBER,
 CAMA NUMBER CONSTRAINTS FK_CAMA_ENF REFERENCES OCUPACION1(CAMA)
);
             INSERT INTO ENFERMO1 VALUES(1, 'FRANKESTEIN', 'EL PEQUEÑO', '25/05/1987', 'M', 4, 4);

SELECT * FROM HOSPITAL1;
SELECT * FROM DOCTOR1;
SELECT * FROM SALA1;
SELECT * FROM PLANTILLA1;
SELECT * FROM OCUPACION1;
SELECT * FROM ENFERMO1;

SELECT * FROM USER_CONSTRAINTS
       WHERE TABLE_NAME IN ('HOSPITAL1', 'DOCTOR1', 'SALA1', 'PLANTILLA1', 'OCUPACION1', 'ENFERMO1');
       
 
 

                
